[package]
name = "ani-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.5"
actix-web = "4.0"
serde = "*"

# stardict = "0.2.1"
# actix-files = "0.6.6"
# actix-multipart = "0.7.2"